name: 'Fetch Secrets'
description: 'Fetch secrets from Azure Key Vault and set them as variables'
inputs:
  vault-name:
    description: 'The name of the Azure Key Vault'
    required: true
    type: string
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'icon.png'
  color: 'blue'
